# Generated by Django 6.0.6 on 2026-06-13 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('mineral', 'Минеральное'), ('organic', 'Органическое'), ('universal', 'Универсальное')], default='universal', max_length=20, verbose_name='Тип удобрения')),
                ('npk_ratio', models.CharField(help_text='Например: 10-10-10', max_length=20, verbose_name='Состав NPK')),
                ('concentration_ml_per_liter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Концентрация (мл на 1 литр воды)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Удобрение',
                'verbose_name_plural': 'Удобрения',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('latin_name', models.CharField(blank=True, max_length=100, verbose_name='Латинское название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('growth_phase', models.CharField(choices=[('growth', 'Рост'), ('flowering', 'Цветение'), ('rest', 'Покой')], default='growth', max_length=20, verbose_name='Фаза роста')),
                ('feeding_interval_days', models.PositiveIntegerField(default=14, verbose_name='Подкормка раз в N дней')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('dosage_ml', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Дозировка (мл)')),
                ('next_feeding_date', models.DateField(verbose_name='Следующая подкормка')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.fertilizer', verbose_name='Удобрение')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'График подкормки',
                'verbose_name_plural': 'Графики подкормок',
            },
        ),
    ]
